name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set image variables
      run: |
        echo "IMAGE_NAME=my-social-media" >> $GITHUB_ENV
        echo "TAG=v1" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$TAG

    - name: Docker Push to Registry
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$TAG

    - name: Notifying through slack (IF Successful)
      if: ${{ !failure() }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text": "The Docker Worflow pipeline was successful!!"}' \
        $SLACK_WEBHOOK_URL    

    - name: Notifying through slack (IF Failure!)
      if: ${{ failure() }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text": "The Docker Worflow pipeline was not successful!!"}' \
        $SLACK_WEBHOOK_URL   
