name: start-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Setting up Python Dependencies
        uses: actions/setup-python@v6.0.0

      - name: Install Dependencies For the application
        run: pip install -r requirements.txt

      - name: Run the test
        run: python3 -m pytest tests/ -v
          
      - name: Notifying through slack (IF Successful)
        if: ${{ !failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "The CI pipeline was successful!!"}' \
          $SLACK_WEBHOOK_URL

      - name: Notifying through slack (IF Failure)
        if: ${{ failure() }}
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          playload: |
            { 
            "text": "The CI pipeline was not successful! ${{ github.repository }} on ${{ github.ref }}"
            }
          
